@IsTest
public class TestTest {
       	
     		private static testmethod void test01() {
       		Test.startTest();        
       		TestCoverage testClass = new TestCoverage();
        	testClass.testCoverageOnly01();
        	testClass.testCoverageOnly02();
        	testClass.testCoverageOnly03();
        	testClass.testCoverageOnly04();
        	testClass.testCoverageOnly05();
			testClass.testCoverageOnly06();
			testClass.testCoverageOnly07();
			testClass.testCoverageOnly08();
			testClass.testCoverageOnly09();
			testClass.testCoverageOnly10();
			testClass.testCoverageOnly11();
			testClass.testCoverageOnly12();
			testClass.testCoverageOnly13();
			testClass.testCoverageOnly14();
			testClass.testCoverageOnly15();
			testClass.testCoverageOnly16();
			testClass.testCoverageOnly17();
			testClass.testCoverageOnly18();
			testClass.testCoverageOnly19();
			testClass.testCoverageOnly20();
			testClass.testCoverageOnly21();
			testClass.testCoverageOnly22();       
			testClass.testCoverageOnly23();
			testClass.testCoverageOnly24(); 
			testClass.testCoverageOnly25();
			testClass.testCoverageOnly26();       
			testClass.testCoverageOnly27();
			testClass.testCoverageOnly28(); 
			testClass.testCoverageOnly29();
			testClass.testCoverageOnly30();
        Test.stopTest();
    }
}